### ISSUE TITLE
Add destination folder

### ISSUE THREAD

**Issue by davidverweij** [davidverweij/csv2docx#13]
As is, I couldn't find a way to add a destination folder, as docx-mailmerge requires a [ZipFile destination](https://github.com/Bouke/docx-mailmerge/blob/261bca9939b8660fadd0365461e3c7225fe2fd31/mailmerge.py#L126). A quick test showed that it doesn't bite on a given path. Hence, I suggest we post-processes the output, by - once it is generated - moving it to a specific subfolder. We can use [shutil](https://docs.python.org/3/library/shutil.html#shutil.move) for this. 

Actually, I would argue we create a 'result' folder by default to keep the directory clean (expecting more than 1 .docx to be created). We could add an argument if a different folder is preferred to be used.

Thoughts?

**Comment by jawrainey** [comment]
@davidverweij -- I agree that a result folder (or "output"?) in the root directory would be ideal, but imho should not be committed to the repo (so added to the git ignore), and also agree that adding an argument is required.

As for implementation, have you tried updating [`write`](https://github.com/davidverweij/csv2docx/blob/master/csv2docx/cli.py#L46) to directly include the path, e.g. `docx.write(f"./results/{counter}.docx")`? This works for me, and would simplify the above proposed used of shutil, etc.

Let me know if that works for you too -- it requires that the directory `results` exists so make sure it's created first.

**Comment by jawrainey** [comment]
I've added a draft demo for you to test/review of outputting the files to _any_ given path that uses pathlib (from python 3.4).

**Comment by davidverweij** [comment]
Ah yes, I see now that ZipFile takes paths or pathlike objects as a parameter. Still, wondering why a 'quick' path string didn't work before - perhaps due to Python 2.7? Either way, I'll have a look at the demo soon. 

Regarding the .gitignore, perhaps we can (for now) set an output folder, and add that to the .git ignore. Then, for each use, a subfolder can be created in that output folder - perhaps using a timestamp in combination with the name of the .csv or .docx file used. This could be default behaviour. A parameter could allow an alternative path.

**Comment by jawrainey** [comment]
I realised that as we ignore `docx` files then we might not need to update the gitignore 👍

**Comment by davidverweij** [comment]
Actually, we are ignoring numbered .docx - so if we were to explore #16 we might need to add any .docx and except the example.docx in tests/data

**Comment by salmannotkhan** [comment]
I am done with this. but i have a question what to do if specified directory is not available??

**Comment by davidverweij** [comment]
@salmannotkhan , we are working on this in the master/output branch, see the PR #18 . Feel free to add your suggestion in the discussion there.

**Comment by salmannotkhan** [comment]
should we create the directory or throw an error??

**Comment by davidverweij** [comment]
What do you reckon? Any pro/cons to either approach?

**Comment by salmannotkhan** [comment]
i guess we should create directory to make hassle free experience

**Comment by jawrainey** [comment]
@salmannotkhan -- the hassle free experience of creating a directory (including nested directories) is implemented in [#18](https://github.com/davidverweij/csv2docx/pull/18/files#diff-943d1d6d09f3f957ed3d46fd8acede0bR16-R19). This also means we don't have to concern ourselves with throw/catching issues. Maybe you can pull down those changes to verify that they're working?

**Comment by salmannotkhan** [comment]
i guess we don't that userdefined function instead of that we can use os library
`if not os.path.isdir(output):
            os.makedirs(output) `

**Comment by jawrainey** [comment]
@salmannotkhan -- have you had a look at the implementation in that PR [see it here](https://github.com/davidverweij/csv2docx/blob/cb3c373a4d0a783640c6ff8a675dc9be76df549e/csv2docx/csv2docx.py#L6-L19). It uses the `pathlib` library, which is the recommended (python 3+) approach over using the `os` library.

**Comment by salmannotkhan** [comment]
ok then that's good also
