### ISSUE TITLE
Rebranding and packaging

### ISSUE THREAD

**Issue by jawrainey** [davidverweij/csv2docx#5]
Currently `docx-csv-mailmerge` is quite long and does not reflect the intention of the library and gives a shout-out to a dependency. PEP-423 advises [using a single name](https://www.python.org/dev/peps/pep-0423/#use-a-single-name) unless it is part of a larger library, e.g. [django-pipeline](http://pypi.python.org/pypi/django-pipeline/) and only then are hyphen's recommended. 

I propose that we rename the project/library to `csv2docx` as inspired by [`docx2pdf`](https://github.com/AlJohri/docx2pdf). Do you have any alternative suggestions?

## What needs changed

1. Rename the repo from `docx-csv-mailmerge` to `csv2docx`
2. Change Attributes in the [`pyproject.toml`](https://github.com/davidverweij/docx-csv-mailmerge/blob/master/pyproject.toml#L2), e.g. `name`, `homepage` & `repository`
3. Rename `docx-csv-mailmerge.py` to `cli.py`
4. Move `cli.py` to `/csv2docx/cli.py`
5. Add an `__init__.py` to `/csv2docx/`
6. Remove `if __name__ == "__main__":` from `cli.py` (no longer needed)
7. Move example.csv and example.docx to `/tests/data/` for future testing purposes and to clean the folder structure up a bit
8. Change `my-script` in `tool.poetry.scripts`  to `convert = 'csv2docx.cli:generatedocx'` 

The above changes will simplify running the script locally:

    poetry run convert -t tests/data/example.docx -c tests/data/example.csv

If you try to import and use the new package as:

    from csv2docx.cli import generatedocx

It will work -- great success. But if you invoke the method:

    generatedocx("tests/data/example.docx", "tests/data/example.csv", ";")

I suspect this won't work since generatedocx is a click CLI.  The main conversion logic will need to be moved to a new method to share between the CLI and library. Maybe that should be a separate issue?

**Comment by davidverweij** [comment]
Makes sense, and I like the csv2docx. I will rename the repo first following [GitHub Guidelines(https://help.github.com/en/github/administering-a-repository/renaming-a-repository) for point 1 and 2, and will branch out for the packaging

**Comment by davidverweij** [comment]
Renamed the repo. Strongly recommend to update the remote URL (see [here](https://help.github.com/en/github/using-git/changing-a-remotes-url), e.g.:

`git remote set-url origin https://github.com/davidverweij/csv2docx.git`

**Comment by davidverweij** [comment]
Packaging in a new branch, see https://github.com/davidverweij/csv2docx/tree/repacking

**Comment by davidverweij** [comment]
Confirmed that 
`convert("tests/data/example.docx", "tests/data/example.csv", ";")`
will not work without CLI. Will open a new issue to resolve that.

**Comment by jawrainey** [comment]
FYI: you can test the method by passing the import/running as a string (via `-c`) as:

    python -c 'from csv2docx.cli import convert; convert("tests/data/example.docx", "tests/data/example.csv", ";")'
