### ISSUE TITLE
Seperate CLI and main logic

### ISSUE THREAD

**Issue by davidverweij** [davidverweij/csv2docx#9]
As expected in Issue #5 , we need to separate the logic to allow both CLI and package import use.

## What I expect we need to do
- Extract the convert() method to a separate method, which can then be imported by package import.
- Add a call to that method within the convert(), and as such acts as a wrapper for the CLI.

**Comment by jawrainey** [comment]
@davidverweij -- can we add tests for both the library and CLI in the response to this issue? There is an [excellent blog post](https://cjolowicz.github.io/posts/hypermodern-python-02-testing/) on how to write tests using modern practices. By chance, this blog post also implements a CLI and library 👍

**Comment by salmannotkhan** [comment]
can you tell me why we're importing sys library ?

**Comment by jawrainey** [comment]
@salmannotkhan good find -- it seems that I accidentally left in when I did a refactor in [PR 4](https://github.com/davidverweij/csv2docx/pull/4/). The sys library was previously used to parse command line input, e.g. [`sys.argv[1]`](https://github.com/davidverweij/csv2docx/pull/4/files#diff-a0326265bd8e99a9d12abd88de436f5fL43) before we moved to click. This would have automatically been found if we had used linting 👍 (will open an issue related to linting now).

**Comment by salmannotkhan** [comment]
i finished refactoring the code

**Comment by salmannotkhan** [comment]
can you guide me how can i contribute now to your repo

**Comment by jawrainey** [comment]
@salmannotkhan -- excellent! Feel free to make a PR and I can have a look (also @davidverweij) and we can expand on the discussion in the PR? Great work 👍

**Comment by jawrainey** [comment]
If you click on [pull requests](https://github.com/davidverweij/csv2docx/pulls you'll be able to 'compare changes' and should be able to create a pull request from there

**Comment by salmannotkhan** [comment]
Done created pull request

**Comment by salmannotkhan** [comment]
I was thinking we can more simplify this module by removing poetry and using direct csv2docx-cli.py --parameters....
and including requirements.txt for all the dependencies

**Comment by jawrainey** [comment]
Great job @salmannotkhan -- Dave has merged your PR into master 👍 

Regarding simplifying the module and use of `poetry`. [Poetry](https://python-poetry.org/) is great for dependency management and includes all dependencies (similar to a `requirements.txt`) in its [lock file](https://github.com/davidverweij/csv2docx/blob/master/poetry.lock). As you've likely experienced, once you run `poetry install/shell` it creates a virtual environment outside of your location for running our library in isolation. This (imho) greatly improves the development experience.

Two things worth nothing: (i) poetry simplifies publishing the library to pypi and (ii) requires a significant number of files than using [pipfiles](https://github.com/pypa/pipfile) or `requirments.txt`.

**Comment by salmannotkhan** [comment]
So the end user doesn't have to install poetry they means??

**Comment by salmannotkhan** [comment]
And one more thing. I simply this even more if we remove folder csv2docx and place files in root directory

**Comment by davidverweij** [comment]
Using poetry does make publishing to, e.g. PyPi, rather simple process,  see also [here](https://johnfraney.ca/posts/2019/05/28/create-publish-python-package-poetry/). Poetry also currently helps with the development of this repo - for example when we went from Python 2.7 to 3. I argue we should stick with this approach for now as we are still adding more dependencies in this development stage.

**Comment by jawrainey** [comment]
@salmannotkhan -- good question. The reason for having `csv2docx` in a folder rather than root is because (i) this groups all the code together (e.g. the library and CLI) into one [module](https://docs.python-guide.org/writing/structure/); and (ii) makes it easier to test, import and use the module.

There are two options for folder structure of [packages](https://docs.python-guide.org/writing/structure/#packages) that are common practice in python nowadays: (i) creating a folder of the modules name (as we do and [mypy](https://github.com/python/mypy)); and (ii) creating a root `src/` folder where the module is inside it, e.g. see [click](https://github.com/pallets/click), [flask](https://github.com/pallets/flask), [marshmellow](https://github.com/marshmallow-code/marshmallow), etc. 
is to use `src/MODULE_NAME/codebase`. 

There are some [opinions](https://docs.python-guide.org/writing/structure/#the-actual-module) on what best practices are for small projects like ours, but given we don't know how it will change we have set the package structure in place for future proofing and learning 👍

**Comment by salmannotkhan** [comment]
i guess then we should change folder name to src because `import csv2docx.csv2docx` creates confusion

**Comment by jawrainey** [comment]
I agree with you there and ideally we would like to have the library be used as `from csv2docx import convert` 👍

**Comment by salmannotkhan** [comment]
to use `from csv2docx import convert` we have to put module file in root directory

**Comment by jawrainey** [comment]
Not necessarily -- see [this example](https://github.com/cjolowicz/hypermodern-python) where it's [imported in tests as above](https://github.com/cjolowicz/hypermodern-python/blob/master/tests/test_wikipedia.py#L7). How we can achieve that ... I am uncertain. Maybe that's something you can look in to @salmannotkhan ? Feel free to open another issue where we can expand on this discussion?

**Comment by salmannotkhan** [comment]
I guess [https://github.com/cjolowicz/hypermodern-python/blob/400386bd73109fa2163ddfd05c05b6dc7d316afc/pyproject.toml#L48](this line) is making it possible

**Comment by salmannotkhan** [comment]
Done. Creating new PR...
